---
- hosts: kubernetes
  become: yes
  tasks:
    - name: installing apache httpd
      yum:
         name: httpd
         state: latest
    - name: enable and start httpd
      service:
         name: httpd
         state: started
         enabled: yes
    - name: craete file index.html
      file:
        path: /var/www/html/index.html
        state: touch
    - name: add line in index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "Hello World !!!"
